# Generated by Django 5.2.8 on 2025-11-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
